name: Test workflow

on:
  push:
    branches:
      - dev

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Git fetch test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0

      - name: Switch git branch
        run: git switch main

      - name: Display git flow
        run: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline
