name: Version

on:
  push:
    branches:
      - main
      
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Setup Git user
        shell: bash
        run: |
          git config --global user.email "kazuking.1911@gmail.com"
          git config --global user.name "108yen"
          
      - name: Install dependencies
        run: pnpm install

      - name: Version Update
        run: |
          pnpm changeset version
          git add .
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "ci(changelog): update version"
            git push
          fi