name: Version

on:
  push:
    branches:
      - main
      
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Version
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Git user
        run: |
          git config --global user.email "kazuking.1911@gmail.com"
          git config --global user.name "108yen"
          
      - name: Install dependencies
        run: pnpm install
          
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: "Update version"
          commit: "ci(changesets): update version"
          setupGitUser: false
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release tag
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          pnpm changeset tag
          git push --follow-tags

      # - name: Version Update
      #   run: |
      #     pnpm changeset version
      #     git add .
      #     changed=$(git diff --staged --name-only | grep -q . && echo true || echo false)
      #     echo "changed=$changed" >> $GITHUB_ENV

      # - name: Commit changes
      #   if: env.changed == 'true'
      #   run: |
      #     git commit -m 'ci(changelog): update version'
      #     git push

      # - name: Release tag
      #   if: env.changed == 'true'
      #   run: |
      #     pnpm changeset tag
      #     git push --follow-tags

